### ISSUE TITLE
Wrong delimiter for XML header in protocol.py

### ISSUE THREAD

**Issue by the-smart-home-maker** [gpulido/python-selve#1]
Hi there,

I really love the idea of this project! I found a bug in protocol.py on line 92:

Instead of
`msgs = xmlstr.split('<?xml version="1.0"? encoding="UTF-8">')`
there should be
`msgs = xmlstr.split('<?xml version="1.0" encoding="UTF-8"?>')`
in order to make it work.

Best regards
Dani California

**Comment by gpulido** [comment]
Hello @danicalifornia 
Thanks for the report. It is strange as it was working on my home assistant installation using [Homeassistant-Selve](https://github.com/gpulido/homeassistant-selve). 
However I've fixed the header protocol and published on pypi. Version v.1.1.1
I will close this, but please feel free to reopen it if there are more related issues.
Gabriel
